pipeline {

    agent {
        docker { image 'python:2.7.16-slim' }
    }

    stages {
        stage('Build') {
	    when {
		changeset "**/vote/**"
	    }
            steps {
                echo 'Building/compiling vote app..'
                dir('vote') {
                    sh 'pip install -i requirements.txt'
                }
            }
        }
        stage('Test') {
	    when {
		changeset "**/vote/**"
	    }
            steps {
                echo 'Performing Unit Tests on vote app..'
                dir('vote') {
                    sh 'nosetests -v'
                }
            }
        }
    }
    post {
        always {
            echo 'Build pipeline for vote is complete!'
        }
    }
}
