pipeline {

    agent {
	docker { 
	    image 'maven:3.6.1-jdk-8-alpine' 
	    args '-v $HOME/.m2:/root/.m2'
	} 
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building/compiling worker app..'
		dir('worker') {
		    sh 'mvn compile'
		}
            }
        }
        stage('Test') {
            steps {
                echo 'Performing Unit Tests on worker app..'
		dir('worker') {
		    sh 'mvn clean test'
		}
            }
        }
        stage('Deploy') {
            steps {
                echo 'Packagin worker app..'
		dir('worker') {
		    sh 'mvn package'
		}
            }
        }
    }
    post {
        always {
	    echo 'Build pipeline for worker is complete!'
	}
    }
}
