pipeline {
    agent any

    tools {
	maven 'Maven 3.8.1'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building/compiling worker app..'
		dir('worker') {
		    sh 'mvn compile'
		}
            }
        }
        stage('Test') {
            steps {
                echo 'Performing Unit Tests on worker app..'
		sleep 5
            }
        }
        stage('Deploy') {
            steps {
                echo 'Packagin worker app..'
		sleep 3
            }
        }
    }
    post {
        always {
	    echo 'Build pipeline for worker is complete!'
	}
    }
}
